### ISSUE TITLE
Suggestions about style

### ISSUE THREAD

**Issue by bernielxy** [carolinezhao/front-end-learning#1]
For **Repo**

- use [.gitignore](https://www.gitignore.io) to omit .DS_store

For **Image Gallery**

- 整体居中

- 鼠标悬浮即切换，不需要点击

- 切换的标签大小保持一致

**Comment by carolinezhao** [comment]
Thank you for your suggestion :)

**Comment by carolinezhao** [comment]
Thank you for your suggestion :)
